services:
  switchbot-climate:
    image: ghcr.io/watsona4/switchbot-climate:latest
    build: .
    restart: unless-stopped
    volumes:
      - ./config.yaml:/data/config.yaml:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
